# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 1
formats: all
sphinx:
  configuration: docs/conf.py
build:
  os: ubuntu-20.04
  tools:
    python: "3.11" 

python:
  install:
    - requirements: docs/requirements.txt
